#server.port=8081
#
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://39.106.64.16:3306/group_seven?useUnicode=true&characterEncoding=utf-8
#spring.datasource.username=group_seven
#spring.datasource.password=Hebutgo123456!

server:
  port: 8081

spring:
  datasource:
    username: *****
    password: **************
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://*********************
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      # ????????????????????
      max-wait: 60000
      # ???ü????ò??????μ??????????????????????λ?????
      time-between-eviction-runs-millis: 60000
      # ??????????????????С??????????λ?????
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # ??PSCache??????????????????PSCache???С
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # ???ü??????????filters????????????sql???????'wall'????????
      filters: stat,wall
      # ???connectProperties????????mergeSql???????SQL???
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # ??????DruidDataSource????????
      use-global-data-source-stat: true

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1 # 逻辑已删除值(默认是 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认是 0)
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: shop.demo.entity
  # 配置sql打印日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

